# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  name: Default

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'buildAndPush'
        containerRegistry: 'luizexampleacr'
        repository: 'luizunyleya'
        dockerfile: '$(Build.SourcesDirectory)/azure-vote/Dockerfile'
        tags: |
              $(tag)
              $(Build.SourceBranchName)-$(Build.BuildId)
    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        command: 'login'
        containerRegistry: 'luizexampleacr'
    - task: Docker@2
      displayName: 'Push to ACR'
      inputs:
        command: 'push'
        repository: 'luizunyleya'  
        tags: |
          $(Build.SourceBranchName)-$(Build.BuildId)






